### ISSUE TITLE
workflow在哪下载

### ISSUE THREAD

**Issue by 9h0st** [xiaobocser/Mac-command-wallpaper#10]
貌似没提供对应的Alfred workflow下载

**Comment by 9h0st** [comment]
https://github.com/xiaobocser/Mac-command-wallpaper/releases/tag/v2.1
2.1包 里才有
Readme里面放的2.0里面没有 
有点误导
希望改一下

**Comment by xiaobocser** [comment]
哦哦，谢谢提醒~ 
2.0我好像删了 = =
