### ISSUE TITLE
编程日历显示模糊

### ISSUE THREAD

**Issue by ymqy** [xiaobocser/Mac-command-wallpaper#11]
Mac OS: 10.13.4

Python: 3.6.5 ( install via pyenv )

pip version: pip 10.0.1 from /Users/yeming/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip (python 3.6)

pyenv versions: 
  system
* 3.6.5 (set by /Users/yeming/.pyenv/version)
  3.6.5/envs/hello-3.6.5
  hello-3.6.5

![issue](http://p7uanirx5.bkt.clouddn.com/2018-05-22-7931e182-issue.png)

**Comment by ymqy** [comment]
已解决

**Comment by ymqy** [comment]
brew 没有imagemagick@6.9.9.34 版本，从网上(https://ftp.osuosl.org/pub/blfs/conglomeration/ImageMagick/ImageMagick-6.9.9-34.tar.xz)下载了源代码，自行编译到ImageMagick-6.9.9-34目录中，重命名并移动到 brew 的目录下 /usr/local/Cellar/imagemagick@6/6.9.9-34，执行brew switch imagemagick@6 6.9.9-34。这样就好了，嘻嘻。

**Comment by ymqy** [comment]
brew 没有imagemagick@6.9.9.34 版本，从网上https://ftp.osuosl.org/pub/blfs/conglomeration/ImageMagick/ImageMagick-6.9.9-34.tar.xz
下载了源代码，自行编译到ImageMagick-6.9.9-34目录中，重命名并移动到 brew 的目录下 /usr/local/Cellar/imagemagick@6/6.9.9-34，执行brew switch imagemagick@6 6.9.9-34。这样就好了，嘻嘻。

**Comment by xiaobocser** [comment]
棒棒，赞~
