### ISSUE TITLE
macOS 10.13.3+zsh

### ISSUE THREAD

**Issue by fashioncj** [xiaobocser/Mac-command-wallpaper#3]
$ bash install.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path

**Comment by xiaobocser** [comment]
应该是你bash环境的readlink不是gun版本的，你可以通过`readlink --h`查看一下

**Comment by xythink** [comment]
$ readlink --h
readlink: illegal option -- -

**Comment by fashioncj** [comment]
usage: readlink [-n] [file ...]
Mac 自带的readlink

**Comment by fashioncj** [comment]
`brew install coreutils`

然后将install和wallpaper里面的readlink替换为greadlink就好了
----
ps：这种方法获取到的shell folder不能有空格，换句话说就是wallpaper的绝对路径不能有空格。

**Comment by xiaobocser** [comment]
@xieldy 参考 @fashioncj的方法，安装 gun版本的命令工具

**Comment by xiaobocser** [comment]
@fashioncj  感谢提醒，install.sh已经支持空格文件

**Comment by xiaobocser** [comment]
替换了`install.sh`中`readlink`命令，这样更通用了。

**Comment by xiaobocser** [comment]
@fashioncj 不好意思，我之前草率了，只修改了install.sh文件的一些命令依赖。刚刚我用zsh也执行了一下，发现还有若干问题，所以可能还是给你造成了一些困扰。我这次一并将所有的依赖都修改了，并做了zsh的环境支持。可以重新下载并执行install，这次没有问题了。 谢谢你一直的反馈~

**Comment by fashioncj** [comment]
@xiaobocser 我看了一下代码，兼容性越来越好了。不过环境变量我都手动的添加了昨晚~。 我今晚测试一下crontab 的定时任务会不会有问题。
