### ISSUE TITLE
13寸MacbookPro

### ISSUE THREAD

**Issue by xythink** [xiaobocser/Mac-command-wallpaper#4]
更换的桌面壁纸日历始终显示不完全
<img width="752" alt="2018-02-09 10 53 15" src="https://user-images.githubusercontent.com/22199000/36009529-756b0a0a-0d87-11e8-944a-92b10af25c77.png">

**Comment by xythink** [comment]
是壁纸分辨率大小的问题吗？

**Comment by xiaobocser** [comment]
sorry，犯了个低级错误，分辨率设定错了。。
·最新版已经更新， 谢谢提醒 ~

**Comment by xiaobocser** [comment]
感觉用到合成壁纸命令的人不多嗯 ^ ^ 
可能是`安装依赖`比较繁琐吧
