### ISSUE TITLE
【BUG】No such file or directory 

### ISSUE THREAD

**Issue by Lxxyx** [xiaobocser/Mac-command-wallpaper#5]
![image](https://user-images.githubusercontent.com/13161470/36202404-a52bcef6-11be-11e8-8646-718ecbcb13a9.png)

**Comment by Lxxyx** [comment]
```bash
python --version
```

output: Python 2.7.10

**Comment by xiaobocser** [comment]
这是环境变量的问题，我在外旅游，不便查看，如果可以您可以自己解决，不难解决。

回家后会修复问题。

**Comment by xiaobocser** [comment]
@Lxxyx 我又仔细看了一下你的问题，你的问题是这样的。
1. 通过看你的截图，`wand`是用`python3`安装的，而不是`python2.7`。
2. 即你的`pip`命令默认是`python3`而不是`python2.7`，所以你的解决方案（**二选一**）：
    1. `pip`修改为`python2.7`的版本，并重新安装`wand`
    2. 将默认的`python2.7`换为`python3`
