### ISSUE TITLE
关于安装wand包可能出现的问题

### ISSUE THREAD

**Issue by 0x5a57** [xiaobocser/Mac-command-wallpaper#6]
请在python2.7下安装wand包

安装wand包提示`PermissionError: [Errno 13] Permission denied`, 请加上`--user`参数

```bash
# 安装python2.7
brew install python
# 在python2.7下安装wand包, 加上--user参数就不会出现权限问题了
pip2 install --user wand
```

在python3下安装, 使用编程日历壁纸命令会提示错误找不到wand包

**Comment by xiaobocser** [comment]
谢谢反馈，`PermissionError: [Errno 13] Permission denied`问题可能和您默认的安装路径有关，一般建议将个人的安装包放到有全部权限的路径下，`brew`默认应该也是这样做的。`python3 `的话，应该是系统自带的版本，可能存在权限的问题。
