### ISSUE TITLE
wallpaper randweb com执行错误

### ISSUE THREAD

**Issue by hantmac** [xiaobocser/Mac-command-wallpaper#7]
Python版本：2.7
MacOs:0.13.3 (17D102)
在所有依赖环境都添加的情况下，执行错误：
Exception TypeError: TypeError("object of type 'NoneType' has no len()",) in <bound method Image.__del__ of <wand.image.Image: (empty)>> ignored

**Comment by xiaobocser** [comment]
能粘贴一些更详细的信息吗，这个问题有点印象，但是记不清了

**Comment by xwal** [comment]
@xiaobocser 我的也是这样

Traceback (most recent call last):
  File "bin/generate_code_calender.py", line 38, in <module>
    main()
  File "bin/generate_code_calender.py", line 34, in main
    composite_image(week_num, pdf_path, pic_path, pic_save_path)
  File "bin/generate_code_calender.py", line 14, in composite_image
    with Image(filename=pdf_path.format(page), resolution=200) as calendar:
  File "/usr/local/lib/python3.6/site-packages/wand/image.py", line 2744, in __init__
    self.read(filename=filename, resolution=resolution)
  File "/usr/local/lib/python3.6/site-packages/wand/image.py", line 2822, in read
    self.raise_exception()
  File "/usr/local/lib/python3.6/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.CorruptImageError: unable to read image data `/var/folders/2l/9fw5crv1775gm0gcntx9b0240000gn/T/magick-82969M-3QIqIhMUA31' @ error/pnm.c/ReadPNMImage/1337
Exception ignored in: <bound method Resource.__del__ of <wand.image.Image: (empty)>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wand/resource.py", line 232, in __del__
  File "/usr/local/lib/python3.6/site-packages/wand/image.py", line 2767, in destroy
TypeError: object of type 'NoneType' has no len()
cp: /Users/qinming/Workspace/Mac-command-wallpaper/composite/code_calendar_wallpaper_09.jpg: No such file or directory
33:48: execution error: Finder got an error: AppleEvent handler failed. (-10000)

**Comment by xiaobocser** [comment]
从报错来看，有两个问题，
1. 看起来是通过 python3版本执行的，而非 python27
2. 这个问题应该是缺少这个 `ImageMagick `
安装方法：
`brew install imagemagick@6`
`export MAGICK_HOME=/usr/local/opt/imagemagick@6`

**Comment by xwal** [comment]
Python2.7也是一样，imagemagick@6是配置好了的
Traceback (most recent call last):
  File "bin/generate_code_calender.py", line 38, in <module>
    main()
  File "bin/generate_code_calender.py", line 34, in main
    composite_image(week_num, pdf_path, pic_path, pic_save_path)
  File "bin/generate_code_calender.py", line 14, in composite_image
    with Image(filename=pdf_path.format(page), resolution=200) as calendar:
  File "/usr/local/lib/python2.7/site-packages/wand/image.py", line 2744, in __init__
    self.read(filename=filename, resolution=resolution)
  File "/usr/local/lib/python2.7/site-packages/wand/image.py", line 2822, in read
    self.raise_exception()
  File "/usr/local/lib/python2.7/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.CorruptImageError: unable to read image data `/var/folders/2l/9fw5crv1775gm0gcntx9b0240000gn/T/magick-964626bCk5rW6SJYj1' @ error/pnm.c/ReadPNMImage/1337
Exception TypeError: TypeError("object of type 'NoneType' has no len()",) in <bound method Image.__del__ of <wand.image.Image: (empty)>> ignored
cp: /Users/qinming/Workspace/Mac-command-wallpaper/composite/code_calendar_wallpaper_09.jpg: No such file or directory
33:48: execution error: Finder got an error: AppleEvent handler failed. (-10000)

**Comment by fashioncj** [comment]
@xiaobocser 我也遇到同样的问题，我觉得是版本更新导致的。你试试将你mac的brew所有包都升级到最新再试试，应该就会报错了。

**Comment by fashioncj** [comment]
wand.exceptions.DelegateError: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pamcmyk32' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r200x200' -dUseCIEColor -dFirstPage=17 -dLastPage=17 '-sOutputFile=/var/folders/2y/2n2y37l55xlfl5079rggms6m0000gn/T/magick-62832LwcKgDPuCAyy%d' '-f/var/folders/2y/2n2y37l55xlfl5079rggms6m0000gn/T/magick-62832cPdNCTF4I0AB' '-f/var/folders/2y/2n2y37l55xlfl5079rggms6m0000gn/T/magick-62832wlTipvMg26S1'' (1) @ error/pdf.c/InvokePDFDelegate/292
Exception TypeError: TypeError("object of type 'NoneType' has no len()",) in <bound method Image.__del__ of <wand.image.Image: (empty)>> ignored

**Comment by AlexanderOnly** [comment]
我也遇到了错误，报错的信息是这样的

wufulunax@AlexanderWu:~$ wallpaper randweb com
Traceback (most recent call last):
  File "bin/generate_code_calender.py", line 38, in <module>
    main()
  File "bin/generate_code_calender.py", line 34, in main
    composite_image(week_num, pdf_path, pic_path, pic_save_path)
  File "bin/generate_code_calender.py", line 14, in composite_image
    with Image(filename=pdf_path.format(page), resolution=200) as calendar:
  File "/usr/local/lib/python3.6/site-packages/wand/image.py", line 2744, in __init__
    self.read(filename=filename, resolution=resolution)
  File "/usr/local/lib/python3.6/site-packages/wand/image.py", line 2822, in read
    self.raise_exception()
  File "/usr/local/lib/python3.6/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.CorruptImageError: unable to read image data `/var/folders/55/0b_lfy390bl6hl14tc6r27cc0000gn/T/magick-27591wPE2MrRhiJ0A1' @ error/pnm.c/ReadPNMImage/1337
Exception ignored in: <bound method Resource.__del__ of <wand.image.Image: (empty)>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wand/resource.py", line 232, in __del__
  File "/usr/local/lib/python3.6/site-packages/wand/image.py", line 2767, in destroy
TypeError: object of type 'NoneType' has no len()
cp: /Users/wufulunax/Mac-command-wallpaper-2.0/composite/code_calendar_wallpaper_10.jpg: No such file or directory
33:48: execution error: “Finder”遇到一个错误：AppleEvent 处理程序失败。 (-10000)

**Comment by xiaobocser** [comment]
大家不好意思，最近有点太忙，没有来的及修复问题。 上午 按 @fashioncj 的方法更新后，的确出现这个问题。 这个问题是 `imagemagick@6`更新后对现有的python调用不兼容导致报错，可惜的是我没有找到可行的代码实现。 如果这周末有时间，我会尽力找到一个解决方案的。

**Comment by kingtami** [comment]
1. 去这个链接下载旧版
https://sourceforge.net/projects/imagemagick/files/old-sources/6.x/6.9/ImageMagick-6.9.6-8.tar.xz/download
2.删除之前安装的 ImageMagick
3.按步骤执行以下命令
tar xvzf ImageMagick-6.9.6-8.tar.gz
cd ImageMagick-6.9.6-8
./configure
make
make install
4.测试效果
我搞了2个中午总算搞好了，心满意足。
@hantmac 感谢你的提问让我看到 @xiaobocser 说到时版本问题

**Comment by xwal** [comment]
@kingtami 谢谢，辛苦了

**Comment by fashioncj** [comment]
@kingtami 验证不通过。报错`wand.exceptions.WandError: wand contains no images `MagickWand-5' @ error/magick-image.c/MagickCompositeImageChannel/2043`

**Comment by kingtami** [comment]
@fashioncj ghostscript 也安装了吗？对了，还有就是我这边要 sudo python ...., 不过应该不是你这个错误，你那个我搜索了下可能是 ghostscript 没安装。

**Comment by xiaobocser** [comment]
谢谢@kingtami  同时也谢谢大家， 大家可以通过这个方法先进行简单的版本切换  `brew switch imagemagick@6 6.9.9-34`  ,  后续我尝试下 @kingtami 的方法，并尝试把这个版本`绑定到文件里`

**Comment by xiaobocser** [comment]
好像也不太行，`brew switch imagemagick@6 6.9.9-34` 应该是需要之前安装过旧版本才可用。 后续还是考虑在文件里融入 @kingtami 提供的版本

**Comment by fashioncj** [comment]
@xiaobocser 你切换回去成功了么？我昨晚切换了没有成功就都卸载了。

**Comment by xiaobocser** [comment]
@fashioncj 我用 `brew switch imagemagick@6 6.9.9-34` 切换后就可用了

**Comment by fashioncj** [comment]
@xiaobocser @kingtami 重新`brew link ghostscript` 就可以了~ 
可以试试`brew create https://svwh.dl.sourceforge.net/project/imagemagick/old-sources/6.x/6.9/ImageMagick-6.9.6-8.tar.xz` 需要删掉brew原来的imagemagic的rb文件，不过这个我昨天测试失败了，好像是环境变量的问题，有空继续测试。

**Comment by WuOtto** [comment]
@kingtami 
参照你说的方法，手动安装旧版本，但是在`make`这一步的时候，报错如下
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       coders/magick_libMagickCore_6_Q16_la-msl.lo
coders/msl.c:101:12: fatal error: 'libxml/parser.h' file not found
#  include <libxml/parser.h>
           ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [coders/magick_libMagickCore_6_Q16_la-msl.lo] Error 1
make: *** [all] Error 2
```

**Comment by WuOtto** [comment]
现在默认安装的版本是`imagemagick@6-6.9.9-44`，所有的依赖都安装了，出错应该是`imagemagick`版本的问题

报错信息如下：
```
Traceback (most recent call last):
  File "tools.py", line 16, in <module>
    with Image(filename=PDF_SOURCE.format(page), resolution=200) as calendar:
  File "/Users/zly/Library/Python/2.7/lib/python/site-packages/wand/image.py", line 2744, in __init__
    self.read(filename=filename, resolution=resolution)
  File "/Users/zly/Library/Python/2.7/lib/python/site-packages/wand/image.py", line 2822, in read
    self.raise_exception()
  File "/Users/zly/Library/Python/2.7/lib/python/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.CorruptImageError: unable to read image data `/var/folders/2t/cpfmvw9n55d82l3rgv55np140000gq/T/magick-29649gb7e3RjFcAyf1' @ error/pnm.c/ReadPNMImage/1344
Exception TypeError: TypeError("object of type 'NoneType' has no len()",) in <bound method Image.__del__ of <wand.image.Image: (empty)>> ignored
```

如果有好的解决办法，请告诉我，O(∩_∩)O谢谢~

**Comment by xiaobocser** [comment]
@hantmac @chaoskyme @fashioncj @AlexanderOnly @kingtami  `imagemagick@6` 问题修复了，使用了新的调用方式，支持最新版本的`imagemagick@6` 。 
**需要注意的是， 新的调用方法，合并的`日历图片`不如以前的方法清晰。如果已经配置好之前方式的话是没必要更新的。如果一直没有解决，可以通过最新版本解决**

**最后感谢 @FoxerLee 提供的解决方案~**

**Comment by hantmac** [comment]
感谢, @xiaobocser
